apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track-prod
resources:
- ../../base

namePrefix: prod-
labels:
- pairs:
    environment: prod

patches:
- path: patch.yaml
- path: nginx.yaml

configMapGenerator:
- name: environment-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=DEBUG
