apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/
- backend/

labels:
- pairs:
    app: dependency-track
    managed-by: kustomize

images:
- name: 187899929694.dkr.ecr.us-east-1.amazonaws.com/edward-ecr
  newTag: backend-v1.0
- name: 187899929694.dkr.ecr.us-east-1.amazonaws.com/edward-ecr
  newTag: frontend-v1.0
